#!/bin/bash


# Default Vars
IFS="/"
filePath="~/secrets/terraform.tfvars.asc"


function usage()
{
    echo "usage: tfsecret [-fp | --file-path path_to_file]"
    exit 0
}

function main()
{
    # Check if required commands exist and file
    if ! test -f "${filePath}"; then
        echo "${filePath} dosen't exist or path is wrong"
        exit 1
    fi

    if ! type "gpg" > /dev/null; then 
        echo "gpg doesn't exist, please install it into path"    
        exit 1
    fi



    # Get file
    # read -ra filePathSplit <<< "$filePath"
    # len="${#filePathSplit[@]}"
    # file="${ADDR[$((len - 1))]}"

    cp $filePath ./terraform.tfvars.asc


    gpg --decrypt --nosymkey-cache --output ./terraform.tfvars ./terraform.tfvars.asc


    # Start Terraform
    terraform plan
    terraform apply


    # Remove Terraform.tfvars
    sleep 60s
    rm ./terraform.tfvars*
    exit 0
}

# flag
while [ "$1" != "" ]; do
    case $1 in
        -fp | --file-path )     shift
                                filePath="$1"                                    
                                ;;
        help )                  shift
                                usage
                                ;;
    esac
    shift
done

main
 