#!/bin/bash


# Default Vars
file="~/secrets/terraform.tfvars.asc"

if ! test -f "${file}"; then
    echo "${file} dosen't exist or path is wrong"
    exit 1
fi

cp $file  .

if ! type "gpg" > /dev/null; then 
    echo "gpg doesn't exist, please install it into path"
    exit 1
fi


gpg --decrypt --nosymkey-cache --output ./terraform.tfvars ./terraform.tfvars.asc


# Start Terraform
terraform plan
terraform apply


# Remove Terraform.tfvars
sleep 60s
rm ./terraform.tfvars*
